### ISSUE TITLE
2.0?

### ISSUE THREAD

**Issue by edasque** [lux4rd0/sense-collector#14]
I’ve been enjoying using sense-collector 1.0.1 for a while, thanks to your work.

I noticed recently that you had pushed a 2.0 image on docker hub a few months back. I don’t see a 2.0 branch, new commits or documentation on GitHub, is that something you will update soon?

**Comment by lux4rd0** [comment]
Hey @edasque - the new version was just pushed out today!! Thanks for hanging in there! I thought I was ready to go but was sidetracked with other projects! Let me know how it works out! Thanks!

**Comment by edasque** [comment]
Do you only support influxDB 2.x? It's unclear from the documentation. I imagine so since you're talking about tokens and moved on from user/password for InfluxDB?

**Comment by lux4rd0** [comment]
> Do you only support influxDB 2.x? It's unclear from the documentation. I imagine so since you're talking about tokens and moved on from user/password for InfluxDB?

Hi @edasque - yep - moved to 2.x - the requirement is on the main page but not explicitly stating that I no longer work with 1.x. Influx stopped supporting that version at the end of 2021, and I was kind of dragging my feed, happy to go along with "what worked." Thankfully, InfluxQL still works quite well in v2, and having Grafana work with it was just a different config in the data source.
