### ISSUE TITLE
Raspberry PI arm build

### ISSUE THREAD

**Issue by wmandra** [lux4rd0/sense-collector#2]
This is really great work! I've rebuilt the docker image for arm so that it can run on a Raspberry Pi which can be found here https://hub.docker.com/r/wmandra/sense-collector

A few issues I ran into: 
copying in jq binary didn't work, just added jq to the apt-get install 
had to grab arm version of websocat (either the build script should just grab this, or download within the Dockerfile)
had to disable health check as the script was missing
for some reason $delay was being calculated as a negative number causing sleep to treat the value as an option, added "| awk -F- '{print $NF}'" to ensure it is always a positive number

Also noticed some items in Grafana dashboards hardcoded and removed those on my installation.

**Comment by lux4rd0** [comment]
@wmandra - Will build an ARM version of this project. I had done some for my WeatherFlow Collector but haven't tested this on my own Pi. Appreciate you outlining your steps above as well as my sleep delay calculation bug.

**Comment by wmandra** [comment]
@lux4rd0 just another quick note. While I did have this running on arm for the Pi, I've since migrated to M1 Mac Mini's. Unfortunately none of the websocat arm64 binaries are compatible currently (I believe due to page size difference on the M1).

**Comment by lux4rd0** [comment]
Hello! The new V2 release now includes both ARM and X86 docker images. Let me know how it works out for you! Thanks!
