### ISSUE TITLE
Wiki - Collector Details - sense-collector - Sense compatible smart plugs Link Dead

### ISSUE THREAD

**Issue by RyanRoberts210** [lux4rd0/sense-collector#22]
Hi, I believe that this is possibly the replacement link...

https://help.sense.com/hc/en-us/articles/360011987134-How-do-I-use-Sense-with-smart-plugs

**Comment by lux4rd0** [comment]
Ah!! Thanks @RyanRoberts210  for the update to the broken link! I updated it!!
