### ISSUE TITLE
Health Check Missing

### ISSUE THREAD

**Issue by bdf0506** [lux4rd0/sense-collector#3]
It looks like the start-health-check.sh file is missing from the repo. This is similar to an item listed in #2 . Was this file intentionally left out, or maybe intended for future growth?

```
sense-init: Starting Health Check
/sense-collector/sense-collector-init.sh: line 103: ./start-health-check.sh: No such file or directory
```

Things still work even when the error is there, but it litters the logs. On initial install, the constant log messages may prevent you from seeing important messages, so it is best to bypass it with a variable:
SENSE_COLLECTOR_DISABLE_HEALTH_CHECK=true

**Comment by edasque** [comment]
I have the same issue

**Comment by lux4rd0** [comment]
Adding to Feature Tracking "To do" stage. I grabbed some framework from one of my other projects and didn't quite get everything added in. Will take a look! Thanks!

**Comment by johntdyer** [comment]
Same issue here

**Comment by samsiam** [comment]
same issue here.  for me, i could not determine it actually worked.  i will try the note above from bdf0506

**Comment by lux4rd0** [comment]
With the release of V2, I've removed the health checks altogether. I'll slowly add items back in, but I'm closing this for now as the new version is brand new from the ground up. Thanks!
