### ISSUE TITLE
Sense Dashboards AIO link broken

### ISSUE THREAD

**Issue by jeff47** [lux4rd0/sense-collector#4]
Not really a bug, but in the readme you reference a project called [Sense Dashboards AIO](https://github.com/lux4rd0/sense-dashboards-aio).  That link is broken.  Did the project die?

**Comment by lux4rd0** [comment]
@jeff47 - not die - but didn't get started. :) I'm a little behind on putting that project out and packaging it up. I'll add it to my to-do list!!

**Comment by lux4rd0** [comment]
With the new release - I'll look at fast-tracking an AIO deployment of this!
