### ISSUE TITLE
Feature Request: Migrate/Add support for InfluxDB v2

### ISSUE THREAD

**Issue by StarkZarn** [lux4rd0/sense-collector#5]
Currently it looks like support is only there for Influx v1. I've tried creating a v1 compatible endpoint in Influx v2 and it doesn't work. I think it'd be great to update this to support the Authorization header with a token and influxv2 buckets!

**Comment by lux4rd0** [comment]
@zemsten Thanks for your request. I thought about making a V2 compatible version - but honestly, there are a fair amount of issues with V2 that limit my prioritization of it. It would require entirely brand new dashboards and queries for Grafana for essentially little difference in end results. If they had kept everything else the same from a query perspective, I would have made the changes from the very start. Happy to add this to my project list of efforts, but until V1 is deprecated - it probably won't make much progress. :)

**Comment by everydaylearner** [comment]
i would appreciate v2 support as well!

**Comment by WeaveHubHQ** [comment]
Me too. I'm trying to convert some of these but this is my first time using Grafana at all, so... not going well lol.

**Comment by lux4rd0** [comment]
New version releases with support for InfluxDB2! Whew!! Only took forever!! :)
