### ISSUE TITLE
Error messages: sleep

### ISSUE THREAD

**Issue by jeff47** [lux4rd0/sense-collector#6]
Hello,
I've got this working but there is a persistent error in the logs:

```
Try 'sleep --help' for more information.

sleep: invalid option -- '1'
```

I went through the .sh scripts and tried to see which call was causing the error, but I couldn't work it out.  But I suspect that if one of the scripts isn't sleeping as it should be, it may be polling much more frequently than designed.

**Comment by jeff47** [comment]
Enabling all the debug options reveals what I think is the problem:

```
sense-collector  | host-performance: Sleeping: -1.4476 seconds
sense-collector  | sleep: invalid option -- '1'
```

I was able to correct this by adding this environmental variable:
`SENSE_COLLECTOR_PERF_INTERVAL: 60`

I think this line in start-host-performance.sh needs a sanity check, as well as a default value for $perf_interval.

`
delay=$(echo "scale=4;(${perf_interval}-($after-$before) / 1000000000)" | bc)
`

**Comment by paradizelost** [comment]
Can also confirm that setting SENSE_COLLECTOR_PERF_INTERVAL does eliminate the error

**Comment by lux4rd0** [comment]
The new version doesn't need the sleep features anymore to handle interactions. Try it out! Thanks!
